#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
from PIL import Image
def main (args):
    """
    main() doc
    """
    try:
        with Image.open("./a.png") as a:
            c=a.crop((0,0,int(a.size[0]/2),int(a.size[1]/2)))
            c=c.rotate(180)
            a.paste(c,(0,0,int(c.size[0]),int(c.size[1])))
            a.save("./b.png")
    except IOError:
        pass
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
