#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import threading
import time
import datetime
class TestThreading(object):
	def __init__(self, interval=1):
		self.interval = interval
		thread = threading.Thread(target=self.run, args=())
		thread.daemon = True
		thread.start()
	def run(self):
		while True:
			# More statements comes here
			print(datetime.datetime.now().__str__() + ' : Start task in the background')
			time.sleep(self.interval)
def main (args):
	"""
	main()
	"""
	tr = TestThreading()
	time.sleep(1)
	print(datetime.datetime.now().__str__() + ' : First output')
	time.sleep(2)
	print(datetime.datetime.now().__str__() + ' : Second output')
	return 0;


if __name__ == "__main__":
	import sys;
	sys.exit(main(sys.argv));
	sys.exit(0);

