#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
documentation
"""
def main (args):
    """
    replacement field names
    """
    print("{a}{b}{c}".format(a="qwer",b="asdf",c="zxcv"));
    print("{}{}{a}{}{}".format(1,2,3,4,a="qwer"));
    print("{}{}{}{}{a}{b}{c}{}{}{}".format(1,2,3,4,4,3,2,1,a="qwer",b="asdf",c="zxcv"));
    print("{0}{1}{2}{3}".format(1,2,3,4));
    print("{3}{2}{1}{0}".format(1,2,3,4));
    print("{0}{1}{2}{3}{3}{2}{1}{0}".format(1,2,3,4));
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
