#!/usr/bin/env bash
#export FLASK_APP=main.py
#export FLASK_DEBUG=0
#export MAIL_SERVER=smtp@gmail.com
#export MAIL_PORT=587
#export MAIL_USE_TLS=1
#export MAIL_USERNAME=ockert8080@gmail.com
#export MAIL_PASSWORD=
APP_RUN_PORT=8000
flask run --port=5000 --host=0.0.0.0
