#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import sqlite3
def main (args):
    """
    main()
    """
    try:
        conn=sqlite3.connect('./db/a.db')
        cur=conn.cursor()
        cur.execute('drop table if exists a')
        cur.execute('create table if not exists a(a integer,b varchar(255))')
        cur.execute('delete from a')
        for a in range(4096):
            cur.execute(f'insert into a(a,b)values({a},"{a}")')
        cur.execute('select * from a order by a')
        for a in cur:
            print(a)
        conn.commit()
        conn.close()
    except Exception as e:
        print(e)
    finally:
        print('done')
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
