#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    a=[];
    a.append(0);
    print(a);
    a=[];
    a.extend([0,1]);
    print(a);
    a=[];
    a.insert(0,0);
    print(a);
    a.insert(0,1);
    print(a);
    a.remove(1);
    print(a);
    print(a.pop());
    print(a);
    a=[0];
    a.clear();
    print(a);
    a=[0,1,2,3,0,1,2,3];
    print(a.index(1));
    print(a.index(1,1));
    print(a.count(1));
    b=a.copy();
    a=[0,1,2,3];
    a.reverse();
    print(a);
    return 0;
if __name__=="__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
