#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
argparse sample
see also getopt
"""
import argparse
def main (args):
    """
    main()
    """
    parser=argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('integers',metavar='N',type=int,nargs='+',help='an integer for the accumulator')
    parser.add_argument('--sum',dest='accumulate',action='store_const',
    const=sum,default=max,help='sum the integers (default: find the max)')
    args=parser.parse_args()
    print(args.accumulate(args.integers))

    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
