#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
import Dom
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    a=Dom.Div()
    b=a.addChild(Dom.Div())
    c=b.addChild(Dom.Div())
    d=b.addChild(Dom.Div())
    e=b.addChild(Dom.Div())
    print(a);
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
