#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import io
#import urllib
#import PIL.Image
import aalib
from PIL import Image
import os
def main (args):
    """
    main() doc
    """
    a=320
    b=200
    #hbar
    c=Image.new("RGBA",(a,b))
    for d in range(0,b):
        for e in range(0,a):
                #img.putpixel((x,y0,(r,g,b))
            c.putpixel(\
                    (e,d),\
                    (\
                        int(255*e/255),\
                        int(255-255*e/255),\
                        int(255-255*d/255),\
                        255*(int(d%32)>16)
                    )\
            )
    #vbar
    d=Image.new("RGBA",(a,b))
    for e in range(0,b):
        for f in range(0,a):
                #img.putpixel((x,y0,(r,g,b))
            d.putpixel(\
                    (f,e),\
                    (\
                        int(255-255*e/255),\
                        int(255*f/255),\
                        int(255-255*f/255),\
                        255*(int(f%32)>16)
                    )\
            )
    #fill
    f=Image.new("RGBA",(a,b))
    for g in range(0,b):
        for h in range(0,a):
                #img.putpixel((x,y0,(r,g,b))
            f.putpixel(\
                    (h,g),\
                    (\
                        255,\
                        0,\
                        255,\
                        255
                    )\
            )
    #comp
    g=Image.alpha_composite(c,d)
    g=Image.alpha_composite(f,g)
    #2vtty
    h,i=os.popen('stty size','r').read().split()#row/col
    h=int(int(h)/2)
    i=int(int(i)/2)
    screen=aalib.AsciiScreen(width=i,height=h)
    g.resize(screen.virtual_size)
    screen.put_image((0,0),g.convert('L'))
    print(screen.render())
    #2png
    g.save("a.png")
    return 0;
if __name__=="__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);



