#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import io
#import urllib
from PIL import ImageChops
from PIL import Image
from PIL import ImageDraw
from PIL import ImageColor
from PIL import ImageFont
import os
import random 
import math
def main (args):
    """
    main() doc
    """
    w=1600
    h=800
    im=Image.new("RGB",(w,h))
    #imgdraw
    draw=ImageDraw.Draw(im,'RGBA')
    for y in range(0,h):
        draw.line(
            (0,y,w,y),
            fill="hsl({}, {}%, {}%)".format(255,100,y/h*25)
        )
    grdstrd=16
    for y in range(0,h,1):
        for x in range(0,w,grdstrd):
            draw.point(
                (x,y),
                fill="hsl({}, {}%, {}%)".format(255,100,25-y/h*25)
            )
    for y in range(0,h,grdstrd):
        draw.line(
            (0,y)+(w,y),
            fill="hsl({}, {}%, {}%)".format(255,100,25-y/h*25)
        )
    fntsz=25
    msgx=16
    msgy=1
    fnt=ImageFont.truetype("./res/ProggyClean.ttf",fntsz)
    idx=0
    msg='sin()'
    draw.multiline_text(
            (im.size[0]-128,0),
            msg,
            font=fnt,
            fill=(255,255,255,32),
            anchor=(0,0),
            align='right'
    )
    #scale
    for x in range(0,24,1):
        draw.line(
                (x,0,x,im.size[1]),
                fill=(255,255,255,int(64*x/24))
        )
    fntsz=10
    msgx=0
    msgy=1
    fnt=ImageFont.truetype("./res/ProggyClean.ttf",fntsz)
    for y in range(0,im.size[1],grdstrd):
        draw.text(
                (4,y),
                str(y),
                font=fnt,
                fill=(255,255,255,32)
        )
    for x in range(0,im.size[0]):
        rw=1
        rh=int(0.75*(1+math.sin(2*(math.pi/4+2*math.pi*x/im.size[0])))*im.size[1]/2+random.randint(0,im.size[1])/16)
        for y in range(0,rh):
            draw.rectangle(
                    (x,h-y)+(x,h-y),
                    fill=(128,128,255,int(255*y/rh))
        )
    del draw
    #2vtty
    row,col=os.popen('stty size','r').read().split()#row/col
    row=int(int(row)/2)
    col=int(int(col)/2)
    #2png
    im.save("a.png")
    return 0;
if __name__=="__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
