#!/usr/bin/env python
"""
flask sockets
"""
from flask import\
		Flask,\
		render_template,\
		jsonify,\
		request,\
		Response,\
		g
from flask_socketio import\
		SocketIO,\
		emit
import datetime
import time
import sqlite3
import json
import random
import math
import os
import threading
#--------------------------------------------------------------------------------
DB='./db/a.db'
#--------------------------------------------------------------------------------
app=Flask(
	__name__,
	static_url_path="",
	static_folder="web/static",
	template_folder="web/templates"
);
socketio=SocketIO(
	app,
	async_mode='threading'#gevent???

)
#--------------------------------------------------------------------------------
@app.before_first_request
def activate_job():
	"""startupjob: todo trigger with requests"""
	def run_job():
		while True:
                    socketio.emit(
                        'log',
                        {
                            #'data':random.randint(0,100)/100
                            'data': math.sin(2*math.pi*datetime.datetime.now().microsecond/1000000)/2+0.5
                        },
                        broadcast=True
                    )
                    time.sleep(0.05)
	thread=threading.Thread(target=run_job)
	thread.start()
@app.route('/')
def index():
	return render_template('index.html')
#--------------------------------------------------------------------------------
@socketio.on('connect')
def test_connect():
	print('socketio: connect')
	emit('log', {'data': 'Connected'})
@socketio.on('disconnect')
def test_disconnect():
	print('Client disconnected')
#--------------------------------------------------------------------------------
def main (args):
	"""
	main()
	"""
	assert(os.path.exists("web/static")),'no folder';
	assert(os.path.exists("web/templates")),'no folder';
	socketio.run(
		app,
		host='0.0.0.0',
		port=5000
	)
	return 0;
#--------------------------------------------------------------------------------
if __name__ == "__main__":
	import sys;
	sys.exit(main(sys.argv));
	sys.exit(0);
#--------------------------------------------------------------------------------


