#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
module doc
"""
import random
import pyfiglet
import math
import os
import io
import aalib
from PIL import Image
from flask import\
        Flask,\
        render_template,\
        jsonify,\
        request\
;
assert(os.path.exists("web/static")),'no folder';
assert(os.path.exists("web/templates")),'no folder';
app=Flask(
    __name__,
    static_url_path="",
    static_folder="web/static",
    template_folder="web/templates"
);
#modify to use path parameters
@app.route('/a',methods=['GET','POST'])
def a():
    #rows,cols=os.popen('stty size','r').read().split()
    rows=    140#int(rows)
    cols=    100#int(cols)
    xa=-     2.0
    xb=      1.0
    ya=     -1.5
    yb=      1.5
    maxIt=   255
    imgx=    cols
    imgy=    rows
    image=Image.new("RGB",(imgx,imgy))
    for y in range(imgy):
        zy=y*(yb-ya)/(imgy-1)+ya
        for x in range(imgx):
            zx=x*(xb-xa)/(imgx-1)+xa
            z=zx+zy*1j
            c=z
            for i in range(maxIt):
                if abs(z)>2.0:break
                z=z*z+c
            image.putpixel((x,y),(i%4*64,i%8*32,i%16*16))
    screen=aalib.AsciiScreen(width=cols,height=rows)
    image.resize(screen.virtual_size)
    screen.put_image((0,0),image.convert('L'))
    return(screen.render())
def main (args):
    """
    main() doc
    """
    app.run();
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
