#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    print([0,1,2,3][0:2]);
    print(list(range(0,3))[0:2]);
    print([0,1,2,3][0:3:2]);
    print(list(range(0,8))[0:7:2]);
    print(list(range(0,8))[0:8]);
    print("0123456789abcdef"[0:8]);
    print(""[0:8:2]);
    a="0123456789abcdef";
    print(a[0:8]);
    print(a[0:len(a)]);
    print(a[0:len(a):2]);
    print(a[0:len(a):len(a)]);
    print(a[0:len(a)]);
    #rev
    print([0,1,2,3][4::-1])
    print(a[len(a)::-1])
    #rev
    print(a[::-1])
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
