#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import io
#import urllib
#import PIL.Image
#import aalib
from PIL import ImageChops
from PIL import Image
from PIL import ImageDraw
import os
def main (args):
    """
    main() doc
    """
    w=320
    h=200
    #hbar
    im=Image.new("RGB",(w,h))
    #imgdraw
    draw=ImageDraw.Draw(im)
    draw.line((0,0)+im.size,fill=128)
    draw.line((0, im.size[1], im.size[0], 0), fill=128)
    del draw
    #2vtty
    row,col=os.popen('stty size','r').read().split()#row/col
    #2png
    im.save("a.png")
    return 0;
if __name__=="__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);



