#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
import sys;
import random;
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    #ctor lst no compr
    il=[1,2,3,4,4,5,6,7,7]
    ol=[]
    for a in il:
        if a % 2 == 0:
            ol.append(a)
    print(ol)
    #ctor lst compr
    ol.clear();
    ol=[a for a in il if a %2==0];
    print(ol);
    #ctor lst compr cpy
    ol.clear();
    ol=[a for a in range(8) if True];
    print(ol);
    ol.clear();
    ol=[a for a in il if random.randint(0,1)];
    print(ol);

    return 0;


if __name__ == "__main__":
    sys.exit(main(sys.argv));
    sys.exit(0);
