"""users table

Revision ID: 6152bbb1f693
Revises: 789c5398e3dd
Create Date: 2019-10-28 05:25:39.577008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6152bbb1f693'
down_revision = '789c5398e3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pspa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.Integer(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Integer(), nullable=True),
    sa.Column('F5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pspa')
    # ### end Alembic commands ###
