"""users table

Revision ID: 7745fe076ae4
Revises: e1a1a4ac5b42
Create Date: 2019-10-28 03:41:53.318653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7745fe076ae4'
down_revision = 'e1a1a4ac5b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YY', sa.Integer(), nullable=True),
    sa.Column('MM', sa.Integer(), nullable=True),
    sa.Column('DD', sa.Integer(), nullable=True),
    sa.Column('HH', sa.Integer(), nullable=True),
    sa.Column('BX_VSO', sa.Float(), nullable=True),
    sa.Column('BY_VSO', sa.Float(), nullable=True),
    sa.Column('BZ_VSO', sa.Float(), nullable=True),
    sa.Column('BT', sa.Float(), nullable=True),
    sa.Column('VSOX', sa.Float(), nullable=True),
    sa.Column('VSOY', sa.Float(), nullable=True),
    sa.Column('VSOZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test8')
    op.drop_table('test5')
    op.drop_table('test3')
    op.drop_table('test2')
    op.drop_table('rewq')
    op.drop_table('wordz')
    op.drop_table('test7')
    op.drop_table('test6')
    op.drop_table('words')
    op.drop_table('asdf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asdf',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test6',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test7',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test5',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.create_table('test8',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nam', sa.VARCHAR(), nullable=True),
    sa.Column('val', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mag')
    # ### end Alembic commands ###
