"""users table

Revision ID: 789c5398e3dd
Revises: 8576ab053fe0
Create Date: 2019-10-28 05:11:11.451410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789c5398e3dd'
down_revision = '8576ab053fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvo_pla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.String(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Integer(), nullable=True),
    sa.Column('F5', sa.Float(), nullable=True),
    sa.Column('F6', sa.Float(), nullable=True),
    sa.Column('F7', sa.Float(), nullable=True),
    sa.Column('F8', sa.Float(), nullable=True),
    sa.Column('F9', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvo_pla')
    # ### end Alembic commands ###
