"""users table

Revision ID: 8576ab053fe0
Revises: 7745fe076ae4
Create Date: 2019-10-28 04:24:05.282747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8576ab053fe0'
down_revision = '7745fe076ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvo_mgd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.Integer(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Float(), nullable=True),
    sa.Column('F5', sa.Float(), nullable=True),
    sa.Column('F6', sa.Float(), nullable=True),
    sa.Column('F7', sa.Float(), nullable=True),
    sa.Column('F8', sa.Float(), nullable=True),
    sa.Column('F9', sa.Float(), nullable=True),
    sa.Column('F10', sa.Float(), nullable=True),
    sa.Column('F11', sa.Float(), nullable=True),
    sa.Column('F12', sa.Float(), nullable=True),
    sa.Column('F13', sa.Float(), nullable=True),
    sa.Column('F14', sa.Float(), nullable=True),
    sa.Column('F15', sa.Float(), nullable=True),
    sa.Column('F16', sa.Float(), nullable=True),
    sa.Column('F17', sa.Float(), nullable=True),
    sa.Column('F18', sa.Float(), nullable=True),
    sa.Column('F19', sa.Float(), nullable=True),
    sa.Column('F20', sa.Float(), nullable=True),
    sa.Column('F21', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvo_mgd')
    # ### end Alembic commands ###
