"""users table

Revision ID: 931ecb69f46c
Revises: 
Create Date: 2019-10-28 06:14:37.065212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931ecb69f46c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YY', sa.Integer(), nullable=True),
    sa.Column('MM', sa.Integer(), nullable=True),
    sa.Column('DD', sa.Integer(), nullable=True),
    sa.Column('HH', sa.Integer(), nullable=True),
    sa.Column('BX_VSO', sa.Float(), nullable=True),
    sa.Column('BY_VSO', sa.Float(), nullable=True),
    sa.Column('BZ_VSO', sa.Float(), nullable=True),
    sa.Column('BT', sa.Float(), nullable=True),
    sa.Column('VSOX', sa.Float(), nullable=True),
    sa.Column('VSOY', sa.Float(), nullable=True),
    sa.Column('VSOZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p10_hvm_pls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.Integer(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Float(), nullable=True),
    sa.Column('F5', sa.Float(), nullable=True),
    sa.Column('F6', sa.Float(), nullable=True),
    sa.Column('F7', sa.Float(), nullable=True),
    sa.Column('F8', sa.Float(), nullable=True),
    sa.Column('F9', sa.Float(), nullable=True),
    sa.Column('F10', sa.Float(), nullable=True),
    sa.Column('F11', sa.Float(), nullable=True),
    sa.Column('F12', sa.Float(), nullable=True),
    sa.Column('F13', sa.Float(), nullable=True),
    sa.Column('F14', sa.Float(), nullable=True),
    sa.Column('F15', sa.Float(), nullable=True),
    sa.Column('F16', sa.Float(), nullable=True),
    sa.Column('F17', sa.Float(), nullable=True),
    sa.Column('F18', sa.Float(), nullable=True),
    sa.Column('F19', sa.Float(), nullable=True),
    sa.Column('F20', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pspa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.Integer(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Integer(), nullable=True),
    sa.Column('F5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvo_mgd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.Integer(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Float(), nullable=True),
    sa.Column('F5', sa.Float(), nullable=True),
    sa.Column('F6', sa.Float(), nullable=True),
    sa.Column('F7', sa.Float(), nullable=True),
    sa.Column('F8', sa.Float(), nullable=True),
    sa.Column('F9', sa.Float(), nullable=True),
    sa.Column('F10', sa.Float(), nullable=True),
    sa.Column('F11', sa.Float(), nullable=True),
    sa.Column('F12', sa.Float(), nullable=True),
    sa.Column('F13', sa.Float(), nullable=True),
    sa.Column('F14', sa.Float(), nullable=True),
    sa.Column('F15', sa.Float(), nullable=True),
    sa.Column('F16', sa.Float(), nullable=True),
    sa.Column('F17', sa.Float(), nullable=True),
    sa.Column('F18', sa.Float(), nullable=True),
    sa.Column('F19', sa.Float(), nullable=True),
    sa.Column('F20', sa.Float(), nullable=True),
    sa.Column('F21', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvo_pla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1', sa.String(), nullable=True),
    sa.Column('F2', sa.Integer(), nullable=True),
    sa.Column('F3', sa.Integer(), nullable=True),
    sa.Column('F4', sa.Integer(), nullable=True),
    sa.Column('F5', sa.Float(), nullable=True),
    sa.Column('F6', sa.Float(), nullable=True),
    sa.Column('F7', sa.Float(), nullable=True),
    sa.Column('F8', sa.Float(), nullable=True),
    sa.Column('F9', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YYYY', sa.Integer(), nullable=True),
    sa.Column('MM', sa.Integer(), nullable=True),
    sa.Column('DD', sa.Integer(), nullable=True),
    sa.Column('VENAU', sa.Float(), nullable=True),
    sa.Column('SECLAT', sa.Float(), nullable=True),
    sa.Column('SECLON', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('trajectory')
    op.drop_table('test')
    op.drop_table('pvo_pla')
    op.drop_table('pvo_mgd')
    op.drop_table('pspa')
    op.drop_table('p10_hvm_pls')
    op.drop_table('mag')
    op.drop_table('cpu')
    # ### end Alembic commands ###
