"""users table

Revision ID: b8c878b61f4a
Revises: 931ecb69f46c
Create Date: 2019-10-29 02:09:19.319959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c878b61f4a'
down_revision = '931ecb69f46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p6IMFBRRTN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YYYY', sa.Integer(), nullable=True),
    sa.Column('DOY', sa.Integer(), nullable=True),
    sa.Column('HR', sa.Integer(), nullable=True),
    sa.Column('RTN', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('p6IMFBRRTN')
    # ### end Alembic commands ###
