#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    print("a" in "asdf");
    print("b" in "asdf");
    print("qwer" in "qwerasdfzxcv");
    print("rewq" in "qwerasdfzxcv");
    print(0 in [0,1,2,3]);
    print(4 in [0,1,2,3]);
    return 0;

if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
