#!/usr/bin/python3
import os
from flask import Flask, request, redirect, url_for, send_from_directory
from werkzeug import secure_filename
from Bio import SeqIO


UPLOAD_FOLDER = './uploads'
ALLOWED_EXTENSIONS = set(['fa'])

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

def handle_fa(filename):
    fa = SeqIO.to_dict(SeqIO.parse(filename, 'fasta'))
    return ', '.join([str(x) for x in fa.keys()])

@app.route('/', methods=['GET', 'POST'])
def upload_file():
    print('ok')
    print(dir(request))
    print("Files:", request.files)

    if request.method == 'POST':
        upfile = request.files['file']
        if upfile and allowed_file(upfile.filename):
            print(upfile.filename)
            filename = secure_filename(upfile.filename)
            upfile.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))            
            return handle_fa(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            #redirect(url_for('upload_file'))

    return '''
    <!doctype html>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
    '''

if __name__ == "__main__":
   app.run(port=5000, debug=True)
