#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
#modify to use globals here for config (PORT etc)
from flask import\
        Flask,\
        render_template,\
        jsonify,\
        request\
;
import os;
assert(os.path.exists("web/static")),'no folder';
assert(os.path.exists("web/templates")),'no folder';
app=Flask(
    __name__,
    static_url_path="",
    static_folder="web/static",
    template_folder="web/templates"
);
#modify to use path parameters
@app.route('/a', methods=['GET', 'POST'])
def a():
    return 'test'
@app.route("/b/<name>")
def b():
    return c
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    app.run();
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
