#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
module doc
"""

#modify to use globals here for config (PORT etc)

import random
import pyfiglet
import math
import os;
import termplotlib as tpl
import numpy
import termtables as tt
from flask import\
        Flask,\
        render_template,\
        jsonify,\
        request\
;
assert(os.path.exists("web/static")),'no folder';
assert(os.path.exists("web/templates")),'no folder';
app=Flask(
    __name__,
    static_url_path="",
    static_folder="web/static",
    template_folder="web/templates"
);
#modify to use path parameters
@app.route('/a', methods=['GET', 'POST'])
def a():
    return line()

def main (args):
    """
    main() doc
    """
    app.run();
    return 0;
def line():
    x=numpy.linspace(0,2*numpy.pi,10)
    y=numpy.sin(x)
    fig=tpl.figure()
    fig.plot(x,y,label="data",width=50,height=15)
    return fig.get_string()
def hhist():
    numpy.random.seed(123)
    sample=numpy.random.normal(size=1000)
    counts,bin_edges=numpy.histogram(sample)
    fig=tpl.figure()
    fig.hist(counts,bin_edges,orientation="horizontal",force_ascii=False)
    return fig.get_string()
def vhist():
    numpy.random.seed(123)
    sample=numpy.random.normal(size=1000)
    counts,bin_edges=numpy.histogram(sample,bins=40)
    fig=tpl.figure()
    fig.hist(counts,bin_edges,grid=[15,25],force_ascii=False)
    return fig.get_string()
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);




