#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import os
import sys
import sqlite3
DBNAME = "db/pioneer.db"
DBPATH = os.path.dirname(os.path.realpath(__file__)) + os.sep + DBNAME
DROPTABLE = "DROP TABLE IF EXISTS mag"
MAKETABLE = (
    "CREATE TABLE IF NOT EXISTS mag ("
    "  dat VARCHAR(32)"
    ")"
)
INS = "INSERT INTO mag VALUES ({dat})"
def main (args):
    """
    main() doc
    """

    try:
        conn = sqlite3.connect(DBPATH)
        conn.execute(DROPTABLE)
        conn.execute(MAKETABLE)
        with open('../res/1973096_p11_hvm_ip_15min.asc') as a:
            for b in a:
                conn.execute(f"INSERT INTO mag(dat) VALUES ('{b.split()[0]}')")
            conn.commit()
        return 0;
    except sqlite3.Error as ex:
        sys.stderr.write(f"Something went wrong.\n{ex}\n")
        return 1
    finally:
        if conn:
            conn.commit()
            conn.close()
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);



