#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
import sys;
import random;
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    for a in range(1,8):
        print(random.randint(0,a),end=" ")
    print("")
    return 0;


if __name__ == "__main__":
    sys.exit(main(sys.argv));
    sys.exit(0);
