#!/usr/bin/env python3
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import csv
import shapely
from shapely.geometry import Point
from shapely.geometry import mapping
from fiona import collection
def main (args):
    """
    main() doc
    """
    schema={'geometry':'Point','properties':{'name':'str'}}
    with collection("./out/a.shp", "w", "ESRI Shapefile", schema) as output:
        with open('../res/worldcities.csv','r') as a:
            b=csv.DictReader(a)
            for c in b:
                d=Point(float(c['lng']), float(c['lat']))
                output.write(
                    {
                        'properties':{
                            'name':c['city_ascii']
                        },
                        'geometry':mapping(d)
                    }
                )
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
