#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    #000
    #from math import sqrt;
    #print(sqrt(4));
    #001
    #import math;
    #print(math.sqrt(4));
    #000
    from math import sqrt as asdf;
    print(asdf(4));
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
