#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
from Person import Person
def main (args):
    """
    main()
    """
    juan=Person('Juan');
    okki=Person('Ockert');
    juan.greet();
    okki.greet();
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
