#!/usr/bin/env python3
# vim: ts=4 sw=4 et:
"""
Module doc
"""
import csv
import shapely
from shapely.geometry import Point
def main (args):
    """
    main() doc
    """
    with open('../res/worldcities.csv', 'r') as a:
        b=csv.DictReader(a)
        for c in b:
            #print(f"{c['lat']},{c['lng']}\n")
            d=Point(float(c['lat']), float(c['lng']))
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
