#!/usr/bin/python2
# -*- coding: utf-8 -*-
"""
Sample standalong qgis raster
"""
import qgis
from qgis.core import *
import sys
app = QgsApplication([],True, None)
app.setPrefixPath("/usr", True)
app.initQgis()
sys.path.append('/usr/share/qgis/python/plugins')
from processing.core.Processing import Processing
Processing.initialize()
from processing.tools import *
import processing
def main (args):
	"""
	main() function
	;args - cli args
	"""
	#lod rstr
	a=QgsRasterLayer("./a.png","apng")
	if a.isValid():
		#attr rstr
		print('Width:  {}'.format(a.width()))
		print('Height: {}'.format(a.height()))
		print('Extent: {}'.format(a.extent().toString()))
		print('Bands:  {}'.format(a.bandCount()))
		print('X:	  {}'.format(a.rasterUnitsPerPixelX()))
		print('Y:	  {}'.format(a.rasterUnitsPerPixelY()))
	else:
		print("Invalid raster")
	#stat stdout
    	print(
	    processing.runalg(
		    "qgis:rasterlayerstatistics",
		    {
			"INPUT":"./a.png"
		    }
	    )
	)
	print("Output generated at ./a.html")
	#stat file
	processing.runalg(
	    "qgis:rasterlayerstatistics",
	    {
		'INPUT': './a.png',
		'OUTPUT_HTML_FILE': './a.html'
	    }
	)
	#proc rtr...
        processing.alglist()
	return 0;
if __name__ == "__main__":
	import sys;
	sys.exit(main(sys.argv));
	sys.exit(0);



