#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Generate sample csv
"""
def main (args):
    """
    main()
    """
    with open("./a.csv","w") as a:
        a.write("\"lat\",\"lng\"\n")
        for b in range(0,32,1):
            a.write("{},{}\n".format(b,b))
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
