#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    print(r"\x1B[38;5;<fg>m & \x1B[48;5;‹bg›m:", end="\n\n")

    for n in range(0,8):
        print(f"\x1B[38;5;15m\x1B[48;5;{n}m  {n:2d}  \x1B[m", end=" ")
    print()
    for n in range(8,16):
        print(f"\x1B[38;5;0m\x1B[48;5;{n}m  {n:2d}  \x1B[m", end=" ")
        print()
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
