#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
from PIL import Image
def main (args):
    """
    main() doc
    """
    try:
        with Image.open("./a.png") as a:
            c=2#delta
            c%=a.size[0]
            d=a.crop((0,0,c,int(a.size[1])))
            e=a.crop((c,0,int(a.size[0]),int(a.size[1])))
            a.paste(d,(a.size[0]-c,0,a.size[0],a.size[1]))
            a.paste(e,(0,0,e.size[0],e.size[1]))
            a.save("./b.png")
    except IOError:
        pass
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
