#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
import sys;
import matplotlib.pyplot as plt
import numpy as np
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    # create 1000 equally spaced points between -10 and 10
    x = np.linspace(-10, 10, 1000)
    # calculate the y value for each element of the x vector
    y = x**2 + 2*x + 2

    fig, ax = plt.subplots()
    ax.plot(x, y)
    plt.show()
    return 0;


if __name__ == "__main__":
    sys.exit(main(sys.argv));
    sys.exit(0);


