#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
module doc
"""

#modify to use globals here for config (PORT etc)

import random
import pyfiglet
import math
import os;
import numpy
import termtables as tt
from flask import\
        Flask,\
        render_template,\
        jsonify,\
        request\
;
assert(os.path.exists("web/static")),'no folder';
assert(os.path.exists("web/templates")),'no folder';
app=Flask(
    __name__,
    static_url_path="",
    static_folder="web/static",
    template_folder="web/templates"
);
#modify to use path parameters
@app.route('/a', methods=['GET', 'POST'])
def a():
    ret=''
    return a()

def main (args):
    """
    main() doc
    """
    app.run();
    return 0;
def a():
    numpy.random.seed(0)
    data=numpy.random.rand(8, 4)
    return tt.to_string(data)
def b():
    header=["a","bb","ccc"]
    data=[[1,2,3],[613.23236243236,613.23236243236,613.23236243236]]
    string=tt.to_string(
        data,
        header=header,
        style=tt.styles.ascii_thin_double,
        padding=(0,1),
        alignment="lcr"
    )
    return string
def c():
    header=["a","bb","ccc"]
    data=[[1,2,3],[613.23236243236,613.23236243236,613.23236243236]]
    string=tt.to_string(
        data,
        header=header,
        style="x0123456789abcd"
    )
    return string
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
