#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Generate test raster
"""
import io
#import urllib
from PIL import ImageChops
from PIL import Image
from PIL import ImageDraw
from PIL import ImageColor
from PIL import ImageFont
import os
import random 
import math
def main (args):
    """
    main()
    """
    w=1024
    h=1024
    im=Image.new("RGB",(w,h))
    #imgdraw
    draw=ImageDraw.Draw(im,'RGBA')
    for y in range(0,h):
        draw.line(
            (0,y,w,y),
            fill="hsl({}, {}%, {}%)".format(255,100,y/h*25)
        )
    grdstrd=16
    for y in range(0,h,1):
        for x in range(0,w,grdstrd):
            draw.point(
                (x,y),
                fill="hsl({}, {}%, {}%)".format(255,100,25-y/h*25)
            )
    for y in range(0,h,grdstrd):
        draw.line(
            (0,y)+(w,y),
            fill="hsl({}, {}%, {}%)".format(255,100,25-y/h*25)
        )
    #2png
    im.save("a.png")
    return 0;
if __name__=="__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
