#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
from termcolor import colored
def main (args):
    """
    main() doc
    """
    print(colored('hello', 'red'), colored('world', 'green'))
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
