#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
Module doc
"""
from PIL import Image
def main (args):
    """
    main() doc
    """
    try:
        with Image.open("./a.png") as a:
            b=a.transpose(Image.FLIP_LEFT_RIGHT)
            b=a.transpose(Image.FLIP_TOP_BOTTOM)
            b=a.transpose(Image.ROTATE_90)
            b=a.transpose(Image.ROTATE_180)
            b=a.transpose(Image.ROTATE_270)
            b.save("./b.png")
    except IOError:
        pass
    return 0;
if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
