#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et:
"""
This is documentation for the *module* (the whole file)
"""
import pyfiglet
def main (args):
    """
    main() Needs more stuff here, in real life.
    """
    ascii_banner = pyfiglet.figlet_format("Hello!!")
    print(ascii_banner)
    return 0;


if __name__ == "__main__":
    import sys;
    sys.exit(main(sys.argv));
    sys.exit(0);
