"""users table

Revision ID: ad6a4009b0c9
Revises: 7d456049bd37
Create Date: 2019-10-23 05:19:48.601686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6a4009b0c9'
down_revision = '7d456049bd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YYYY', sa.Integer(), nullable=True),
    sa.Column('MM', sa.Integer(), nullable=True),
    sa.Column('DD', sa.Integer(), nullable=True),
    sa.Column('VENAU', sa.Float(), nullable=True),
    sa.Column('SECLAT', sa.Float(), nullable=True),
    sa.Column('SECLON', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trajectory')
    # ### end Alembic commands ###
